/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.wcci.interview;

interface PlaneGeometry {
	double area();
	double perimeter();
}

interface Shape {
	default int sides(){
		return 4;
	};
}

class Rectangle implements PlaneGeometry, Shape {
	private double width;
	private double height;
	public Rectangle(double width, double height){
		this.width = width;
		this.height = height;
	}
	public double area(){
		return width * height;
	}
	public double perimeter(){
		return 2*width + 2*height;
	}
}

class Square implements PlaneGeometry, Shape {
	private double side;
	public Square(double side){
		this.side = side;
	}
	public double area(){
		return side * side;
	}
	public double perimeter(){
		return 4 * side;
	}
}

class Circle implements PlaneGeometry, Shape {
	private double radius;
	public Circle(double radius){
		this.radius = radius;
	}
	public double area(){
		return Math.PI * radius * radius;
	}
	public double perimeter(){
		return Math.PI * 2 * radius;
	}
	@Override
	public int sides(){
		return 0;
	}
}

public class App {

    public static void main(String[] args) {
		Rectangle rectangle = new Rectangle(5, 10);
		System.out.println("Area: " + rectangle.area());
		Square square = new Square(5);
		System.out.println("Area: " + square.area());
		Circle circle = new Circle(5);
		System.out.println("Area: " + circle.area());
    }
}
